server:
  port: 17073
# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:mydb
    username: test
    password: test
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true

# Logger Config
logging:
  level:
    com.example.tkmybatis: debug
# MyBatis-Plus 配置该演示无
